# Last Change: 25-Oct-2019.
# Maintainer:  TH

[[plugins]]
repo='NLKNguyen/papercolor-theme'
hook_add='''
'''

[[plugins]]
repo='altercation/vim-colors-solarized'
hook_add='''
'''

[[plugins]]
repo='arcticicestudio/nord-vim'
hook_add='''
'''

[[plugins]]
repo='chriskempson/vim-tomorrow-theme'
hook_add='''
'''

[[plugins]]
repo='cocopon/iceberg.vim'
hook_add='''
'''

[[plugins]]
repo='gosukiwi/vim-atom-dark'
hook_add='''
'''

[[plugins]]
repo='itchyny/landscape.vim'
hook_add='''
'''

[[plugins]]
repo='jacoborus/tender.vim'
hook_add='''
'''

[[plugins]]
repo='jdkanani/vim-material-theme'
hook_add='''
'''

[[plugins]]
repo='joshdick/onedark.vim'
hook_add='''
'''

[[plugins]]
repo='junegunn/seoul256.vim'
hook_add='''
'''

[[plugins]]
repo='nanotech/jellybeans.vim'
hook_add='''
'''

[[plugins]]
repo='nerdpad/dracula-vim'
hook_add='''
'''

[[plugins]]
repo='nightsense/nemo'
hook_add='''
'''

[[plugins]]
repo='rakr/vim-one'
hook_add='''
'''

[[plugins]]
repo='sjl/badwolf'
hook_add='''
'''

[[plugins]]
repo='tomasr/molokai'
hook_add='''
'''

[[plugins]]
repo='tyrannicaltoucan/vim-quantum'
hook_add='''
'''

[[plugins]]
repo='vim-scripts/Wombat'
hook_add='''
'''

[[plugins]]
repo='vim-scripts/sonoma.vim'
hook_add='''
'''

[[plugins]]
repo='vim-scripts/newspaper.vim'
hook_add='''
'''

[[plugins]]
repo='jnurmine/Zenburn'
hook_add='''
'''

[[plugins]]
repo='morhetz/gruvbox'
hook_add='''
'''

[[plugins]]
repo='vim-scripts/dw_colors'
hook_add='''
'''

[[plugins]]
repo='vim-scripts/pyte'
hook_add='''
'''

[[plugins]]
repo='w0ng/vim-hybrid'
hook_add='''
'''

[[plugins]]
repo='yarisgutierrez/ayu-lightline'
hook_add='''
'''

[[plugins]]
repo='nightsense/snow'
hook_add='''
'''

#[[plugins]]
#repo='google/vim-colorscheme-primary'
#hook_add='''
#'''

[[plugins]]
repo='ayu-theme/ayu-vim'
hook_add='''
set background=dark
augroup MyAutoCmd
au MyAutoCmd VimEnter * nested let ayucolor="light"  "mirage dark
au MyAutoCmd VimEnter * nested colorscheme ayu
augroup end
'''
