-- local default_conf = {
--     enable = false,
--     style = {},
--     notify = false,
--     priority = 0,
--     exclude_filetypes = {
--         aerial = true,
--         dashboard = true,
--         -- some other filetypes
--     }
-- }
