require('impatient')
require("options")
vim.cmd("source $HOME/AppData/Local/nvim/viml/maps.vim")
vim.cmd("source $HOME/AppData/Local/nvim/viml/autocmd.vim")
require("plugins")
vim.cmd("colorscheme ayu")
