require('impatient')
require("options")
vim.cmd("source $HOME/AppData/Local/nvim/viml/maps.vim")
vim.cmd("source $HOME/AppData/Local/nvim/viml/autocmd.vim")
require("plugins")
--require('my_plugins.lspconfig')
vim.cmd("colorscheme ayu")
