" Last Change: 23-Feb-2022.

set guifont=Cica:h12,Consolas:h12
set renderoptions=type:directx,renmode:5
set antialias
set linespace=1
if has('kaoriya')
	set ambiwidth=auto
else
	set ambiwidth=double
endif

let ayucolor='light'
colorscheme onedark
if empty(get(g:, 'colors_name', ''))
  colorscheme desert
endif
