" Last Change: 21-Mar-2022.

set guifont=Cica:h12,Consolas:h12
set renderoptions=type:directx,renmode:5
set antialias
set linespace=1

let ayucolor='light'
colorscheme ayu
if empty(get(g:, 'colors_name', ''))
  colorscheme desert
endif

"起動時のウィンドウサイズ
let g:save_window_file = expand('~/.vimwinpos')
augroup SaveWindow
  autocmd!
  autocmd VimLeavePre * call s:save_window()
  function! s:save_window()
    let options = [
      \ 'set columns=' . &columns,
      \ 'set lines=' . &lines,
      \ 'winpos ' . getwinposx() . ' ' . getwinposy(),
      \ ]
    call writefile(options, g:save_window_file)
  endfunction
augroup END

if filereadable(g:save_window_file)
  execute 'source' g:save_window_file
endif

"gvim限定 colorscheme後に書くこと
if has('multi_byte_ime')
  highlight Cursor guifg=#000d18 guibg=#8faf9f gui=bold
  highlight CursorIM guifg=NONE guibg=#ecbcbc
endif
