" Last Change: 26-Sep-2022.

source $HOME/vimfiles/init/useroptions.vim
source $HOME/vimfiles/init/usermaps.vim
source $HOME/vimfiles/init/userautocmds.vim
source $HOME/vimfiles/init/userdein.vim

if !has("gui_running")
    colorscheme ayu
endif

filetype plugin indent on
syntax on
